import os
import logging
import asyncio
import httpx
import re
from quart import Quart, request, jsonify

app = Quart(__name__)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - AGENT - %(levelname)s - %(message)s')

# Cấu hình
OLLAMA_URL = os.getenv("OLLAMA_URL", "http://host.docker.internal:11434/api/generate")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3")
ETL_CONTAINER_NAME = os.getenv("ETL_CONTAINER_NAME", "etl_pipeline")
FUNCTION_FILE_PATH = "/app/function.py"

processing_lock = asyncio.Lock()

# --- CÁC HÀM BỔ TRỢ ---

def read_current_code():
    try:
        with open(FUNCTION_FILE_PATH, "r") as f:
            return f.read()
    except Exception:
        return ""

def write_new_code(code_content):
    try:
        with open(FUNCTION_FILE_PATH, "w") as f:
            f.write(code_content)
        return True
    except Exception:
        return False

def extract_python_code(llm_response: str):
    pattern = r"```python(.*?)```"
    match = re.search(pattern, llm_response, re.DOTALL)
    if match:
        return match.group(1).strip()
    return llm_response.strip()

# --- TÍNH NĂNG MỚI: TEST CODE TRƯỚC KHI LƯU ---
def validate_fix(code_str: str, failed_payload: dict) -> bool:
    """
    Chạy thử code mới trong môi trường cô lập (Sandbox giả) để xem có fix được lỗi không.
    """
    logging.info("Testing the fix generated by AI...")
    
    # Tạo môi trường biến cục bộ để chạy code
    local_scope = {}
    
    try:
        # 1. Compile và thực thi đoạn code string để định nghĩa hàm 'transform'
        exec(code_str, {}, local_scope)
        
        # 2. Kiểm tra xem hàm transform có tồn tại không
        if 'transform' not in local_scope:
            logging.error("Test Failed: AI code does not contain 'transform' function.")
            return False
            
        # 3. Lấy hàm transform ra
        transform_func = local_scope['transform']
        
        # 4. Chạy thử với dữ liệu đã gây lỗi trước đó
        # Nếu hàm chạy mượt mà và trả về dict -> PASS
        result = transform_func(failed_payload)
        
        if isinstance(result, dict):
            logging.info("Test Passed: The fix works on the failed payload!")
            return True
        else:
            logging.error("Test Failed: Function ran but did not return a dictionary.")
            return False
            
    except Exception as e:
        logging.error(f"Test Failed: The new code still throws error: {e}")
        return False

async def call_ollama(prompt):
    async with httpx.AsyncClient(timeout=120.0) as client:
        resp = await client.post(OLLAMA_URL, json={
            "model": OLLAMA_MODEL, "prompt": prompt, "stream": False,
            "options": {"temperature": 0.1}
        })
        return resp.json().get("response", "")

async def restart_etl_container():
    """Trigger Docker Restart theo đúng workflow"""
    logging.info("Triggering Docker Restart for ETL...")
    try:
        proc = await asyncio.create_subprocess_exec(
            "docker", "restart", ETL_CONTAINER_NAME,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
        )
        await proc.communicate()
        logging.info("ETL Container restarted.")
    except Exception as e:
        logging.error(f"Failed to restart Docker: {e}")

# --- API HANDLER ---

@app.route('/transformation_error', methods=['POST'])
async def transformation_error():
    if processing_lock.locked():
        return jsonify({"status": "busy"}), 429

    data = await request.get_json()
    
    async def run_workflow():
        async with processing_lock:
            logging.info("🔧 Starting Workflow: Fix -> Test -> Deploy -> Restart")
            
            # 1. Get info
            current_code = read_current_code()
            error_msg = data['error']
            payload = data['payload_data']

            # 2. Ask Ollama
            prompt = f"Fix this python code based on error: {error_msg}\nCode:\n{current_code}\nRETURN ONLY CODE."
            raw_resp = await call_ollama(prompt)
            fixed_code = extract_python_code(raw_resp)

            # 3. TEST (Bước mới thêm vào)
            if validate_fix(fixed_code, payload):
                # 4. Nếu Test OK -> Ghi file
                write_new_code(fixed_code)
                logging.info("Code saved to disk.")
                
                # 5. Restart (Theo đúng workflow gốc)
                await restart_etl_container()
            else:
                logging.error("Fix rejected because it failed the test.")

    asyncio.create_task(run_workflow())
    return jsonify({"status": "processing"}), 202

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)